/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'pageLink' : IDL.Text,
  'submittedAt' : IDL.Int,
  'problemDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'pageLink' : IDL.Text,
    'submittedAt' : IDL.Int,
    'problemDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };